cacheFolder: ./.yarn/cache

checksumBehavior: reset

compressionLevel: mixed

enableGlobalCache: true

enableHardenedMode: false

globalFolder: ./.yarn/cache/global

nodeLinker: pnpm

yarnPath: .yarn/releases/yarn-4.9.1.cjs
