# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publishing

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: master
            token: NPM_TOKEN
            registry: https://registry.npmjs.org/
          - branch: github-repo
            token: GITHUB_TOKEN
            registry: https://npm.pkg.github.com/
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ matrix.branch }}
    - name: Merge master -> github-repo
      if: matrix.branch == 'github-repo'
      uses: devmasx/merge-branch@1.4.0
      with:
        type: now
        from_branch: master
        target_branch: github-repo
        github_token: ${{ secrets[matrix.token] }}
    - uses: actions/setup-node@v4
      with:
        registry-url: ${{ matrix.registry }}
    - run: yarn config set npmPublishRegistry ${{ matrix.registry }}
      if: matrix.branch == 'github-repo'
    - run: yarn build
      env:
        CI: true
    - name: npm publish
      run: |
        yarn config set npmAuthToken ${{ secrets[matrix.token] }}
        yarn npm publish --access public
